In [1]:
import numpy as np
from numpy.linalg import *
from matplotlib import pyplot as plt
from scipy import spatial as sc
import re

In [3]:
sent_freq = []
with open("sentences.txt", 'r') as f:
    
    s=f.readline()
    while s:
        
        s = s.lower()
        s = re.split('[^a-z]', s)
        while '' in s:
            s.remove('')
        #print(s)

        u = set(s)
        # print(u)
        # sent_index.update(set)
        
        dictionary = {w:s.count(w) for w in u}
        sent_freq.append(dictionary)
        s=f.readline()
        
sent_index = {i:k for i,k in enumerate(set(k for t in sent_freq for k in t.keys()))}

sent_index
#print(sent_index)


{0: 'default',
 1: 'stdout',
 2: 'genes',
 3: 'process',
 4: 'learned',
 5: 'not',
 6: 'domestic',
 7: 'interactive',
 8: 'symbol',
 9: 'predecessor',
 10: 'firmware',
 11: 'part',
 12: 'upgrade',
 13: 'small',
 14: 'error',
 15: 'mountain',
 16: 'will',
 17: 'needing',
 18: 'world',
 19: 'mid',
 20: 'store',
 21: 'members',
 22: 'no',
 23: 'have',
 24: 'releasing',
 25: 'since',
 26: 'simply',
 27: 'content',
 28: 'flow',
 29: 'binary',
 30: 'mac',
 31: 'later',
 32: 'catenates',
 33: 'can',
 34: 'artificial',
 35: 'was',
 36: 'major',
 37: 'and',
 38: 'community',
 39: 'use',
 40: 'closest',
 41: 'arguments',
 42: 'basic',
 43: 'or',
 44: 'receives',
 45: 'changes',
 46: 'versions',
 47: 'command',
 48: 'most',
 49: 'type',
 50: 'wrong',
 51: 'it',
 52: 'switch',
 53: 'vermin',
 54: 'displays',
 55: 'longer',
 56: 'off',
 57: 'has',
 58: 'wild',
 59: 'animals',
 60: 'sequence',
 61: 'releases',
 62: 'possess',
 63: 'deliberately',
 64: 'may',
 65: 'second',
 66: 'high',
 67: 'ancesto

In [50]:
res = np.zeros((22, 254))

for i in range(len(res)):
    for k in range(len(res[0])):
        res[i][k] = 0 if not sent_index[k] in sent_freq[i].keys() else sent_freq[i][sent_index[k]]
        
print(res)

#np.savetxt('test.txt', res, fmt='%.1d')

[[0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [74]:
a = res[0]

def csort(b):
    return sc.distance.cosine(a,b[1])

for i, b in sorted(enumerate(res), key=csort):
    print('сosine(0, ' + str(i) + '): ' + str(sc.distance.cosine(a,b)))

result = {sc.distance.cosine(a,b) : i for i, b in sorted(enumerate(res), key=csort)}

сosine(0, 0): 0.0
сosine(0, 6): 0.7327387580875756
сosine(0, 4): 0.7770887149698589
сosine(0, 21): 0.8250364469440588
сosine(0, 10): 0.8328165362273942
сosine(0, 12): 0.8396432548525454
сosine(0, 16): 0.8406361854220809
сosine(0, 20): 0.8427572744917122
сosine(0, 2): 0.8644738145642124
сosine(0, 13): 0.8703592552895671
сosine(0, 14): 0.8740118423302576
сosine(0, 11): 0.8804771390665607
сosine(0, 8): 0.8842724875284311
сosine(0, 19): 0.8885443574849294
сosine(0, 3): 0.8951715163278082
сosine(0, 9): 0.9055088817476932
сosine(0, 7): 0.9258750683338899
сosine(0, 5): 0.9402385695332803
сosine(0, 15): 0.9442721787424647
сosine(0, 18): 0.9442721787424647
сosine(0, 1): 0.9527544408738466
сosine(0, 17): 0.956644501523794


In [75]:
result

{0.0: 0,
 0.7327387580875756: 6,
 0.7770887149698589: 4,
 0.8250364469440588: 21,
 0.8328165362273942: 10,
 0.8396432548525454: 12,
 0.8406361854220809: 16,
 0.8427572744917122: 20,
 0.8644738145642124: 2,
 0.8703592552895671: 13,
 0.8740118423302576: 14,
 0.8804771390665607: 11,
 0.8842724875284311: 8,
 0.8885443574849294: 19,
 0.8951715163278082: 3,
 0.9055088817476932: 9,
 0.9258750683338899: 7,
 0.9402385695332803: 5,
 0.9442721787424647: 18,
 0.9527544408738466: 1,
 0.956644501523794: 17}